services:
  #MySQL Service
  db:
    image: mysql:8.0.29
    container_name: db
    ports:
      - "3306:5432"
    environment:
      MYSQL_DATABASE: descont_saude
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
